# yuan2resume -- see AGENTS.md for the workflow, docs/GRAMMAR.md for the grammar.
OUT      ?= build
MAIN     ?= main.tex
LATEXMK  ?= latexmk -xelatex -interaction=nonstopmode -outdir=$(OUT)
EXAMPLES := $(wildcard examples/*.tex)

# The README preview is a render of a checked-in example, not a hand-made image:
# it is regenerated by `make preview`, so it can never drift into showing content
# that no file in the repository actually contains.
PREVIEW     ?= examples/academic.tex
PREVIEW_PNG ?= assets/font-commercial.png

.PHONY: all check test examples fonts png preview clean help

all: ## Build $(MAIN) into $(OUT)/
	$(LATEXMK) $(MAIN)

check: ## Definition of done for $(MAIN); non-zero exit if not shippable
	@scripts/check.sh $(MAIN)

test: ## Run positive and negative contract tests for the class
	@scripts/test.sh

examples: ## Build and check every examples/*.tex (page budget 2)
	@rc=0; for f in $(EXAMPLES); do PAGES=2 scripts/check.sh $$f || rc=1; echo; done; exit $$rc

fonts: ## Download the commercial font files used by the original template
	@fonts/download.sh

png: all ## Render every page of $(MAIN) to PNG -- then actually look at it
	gs -q -dNOPAUSE -dBATCH -sDEVICE=png16m -r110 \
	   -sOutputFile=$(OUT)/page-%d.png $(OUT)/$(basename $(notdir $(MAIN))).pdf

preview: ## Regenerate $(PREVIEW_PNG) from $(PREVIEW)
	$(LATEXMK) $(PREVIEW)
	gs -q -dNOPAUSE -dBATCH -sDEVICE=png16m -r300 -dLastPage=1 \
	   -sOutputFile=$(PREVIEW_PNG) $(OUT)/$(basename $(notdir $(PREVIEW))).pdf

clean: ## Remove $(OUT)/
	rm -rf $(OUT)

help: ## List targets
	@grep -hE '^[a-z]+:.*##' $(MAKEFILE_LIST) | sed 's/:.*## /\t/' | expand -t14
